exports.TITLES = {
    en :{
        DEFAULT : "Success",
        GET_GAME_MODES : "Choose game mode",
        GET_APPS_LEADERBOARDS : "Ranking",
        LEADERBOARD_BUTTON_TEXT : "Leaderboard",
        GET_KNOWLEDGE_AREA_CATEGORIES : "Classic",
        GET_CATEGORIES_TITLE : "Select Categories",
        SURPRISE_ME_BUTTON_TEXT : "PLAY RANDOM",
        START_GAME_BUTTON_TEXT : "START",
        KNOWLEDGE_AREA_HEADING : "Knowledge Areas",
        CATEGORY_HEADING : "Categories",
        SELECT_ALL_TEXT : "Select all",
        ALL_TEXT : "All",
        SPIN_PAGE_TITLE : "Quiz", //Spin The Wheel
        SPIN_BUTTON_TEXT : "SPIN", // THE WHEEL
        RESULT_TITLE     : "Results",
        CONGRATULATION_TEXT : "Congratulations",
        PLAY_AGAIN_TEXT : "Play Again",
        LEADERBOARD_TEXT : "Leaderboard",
        CORRECT_COUNT_STREAK_TEXT : "Your chain was {CORRECT_COUNT} correct answers",
        SELECT_NUM_QUESTION_FOR_CLASSIC : "Select number of questions to play",
        LEADERBOARD_TITLE_TEXT : "Leaderboard",
        YOUR_RANK_TEXT : "Your rank",
        GLOBAL_TEXT    : "Global",
        LONGEST_STREAK_TEXT : "Longest Chain",
        LONGEST_CLASSIC_TEXT : "Correct Answers",
        MAXIMUM_COMBAT_TEXT : "Maximum combat win",
        STREAK_TEXT         : "Chain",
        BATTLE_TEXT         : "Battle",
        EMPLEX_TEXT         : "Ranking",
        COMBAT_TEXT         : "Battle",
        CLASSIC_TEXT         : "Classic",
        CORRECT_COUNT_CLASSIC_TEXT : "You answered {CORRECT_COUNT} out of {TOTAL_COUNT} questions correctly.",
        QUESTION_FEEDBACK_TITLE : "View Answer",
        YOUR_ANSWER_TEXT : "Your answer",
        CORRECT_ANSWER_TEXT : "Correct answer",
        ANSWER_EXPLANATION_TEXT : "Explanation of answer",
        GIVE_RATING_TEXT : "Rate this question",
        REVIEW_TEXT : "Reviews",
        LEARNING_TITLE_TEXT : "Learning",
        NEXT_BUTTON_TEXT : "Next",
        QUESTION_TITLE : "Answer Question",
        TIME_OUT_TEXT : "You have been timed out",
        JOURNEY_RESULT_TITLE_TEXT : "Result",
        JOURNEY_RESULT_CONGRATULATION_TEXT: "Congratulations",
        JOURNEY_RESULT_PASS_TEXT: "You have completed the {MODULE_NAME} module",
        JOURNEY_RESULT_TEXT : "Your Results",
        JOURNEY_RESULT_SCORE_TEXT : "Your overall score is ",
        JOURNEY_RESULT_DESCRIPTION_TEXT : "Do the test, earn your first Badge and unlock new games!",
        JOURNEY_RESULT_NEXT_BUTTON_TEXT : "Next",
        JOURNEY_FEEDBACK_TITLE : "Feedback",
        JOURNEY_FEEDBACK_DESCRIPTION_TEXT : "Please rate this {COURSE_NAME} learn before you begin your test!",
        JOURNEY_FEEDBACK_RATING_TEXT : "", //How do you rate this {MODULE_NAME} module?
        JOURNEY_FEEDBACK_TEXT : "How can we further improve this learning journey?",
        JOURNEY_FEEDBACK_BUTTON_TEXT :"Submit & start test",
        JOURNEY_QUIZ_RESULT_TITLE : 'Your Test Result',
        JOURNEY_QUIZ_CONTRATULATION_TEXT : 'Congratulations!',
        JOURNEY_QUIZ_OPPS_TEXT : 'Oh No!',
        JOURNEY_QUIZ_CONTRATULATION_DESCRIPTION_TEXT : 'You have passed the {MODULE_NAME} test.',
        JOURNEY_QUIZ_OOPS_DESCRIPTION_TEXT : 'You did not pass the {MODULE_NAME} test, please try again.',
        JOURNEY_QUIZ_RESULT_TEXT : "Your Results",
        JOURNEY_YOUR_SCORED_TEXT : 'You scored ',
        JOURNEY_PASS_TEXT : 'You have passed the test',
        JOURNEY_FAIL_TEXT : 'You have failed the test',
        JOURNEY_REDO_BUTTON_TEXT : 'Redo Test',
        JOURNEY_FINISH_BUTTON_TEXT : 'Finish Test',
        JOURNEY_MODULE_CONGRATULATION_TEXT : 'Congratulations',
        JOURNEY_MODULE_CONGRATULATION_DESCRIPTION_TEXT : 'Congratulations, you have earned your {MODULE_NAME} badge',
        JOURNEY_NEXT_MODULE_TEXT : 'And unlocked the {NEXT_MODULE_NAME} module',
        JOURNEY_NEXT_MODULE_DESCRIPTION_TEXT : '', //Complete with your colleague to achieve mystry
        JOURNEY_MODULE_NEXT_BUTTON_TEXT : 'Next',
        KNOWLEDGE_AREA_LEARNING_MODULE_TITLE : 'Learn', //'Select Learning Module',
        MODULE_LEARNING_MODULE_TITLE : 'Select Module', //'Select Learning Module',
        KNOWLEDGE_AREA_LEARNING_MODULE_VIEW_BUTTON_TEXT : 'View Module',
        KNOWLEDGE_AREA_LEARNING_MODULE_START_BUTTON_TEXT : 'Start Module',
        KNOWLEDGE_AREA_LEARNING_MODULE_TEXT : 'Learning Module',
        QUESTION_CREATED_BY_INFO_TITLE : 'Author', // 'Question submitted by',
        TOTAL_QUESTION_TEXT : 'Total Question',
        QUESTION_ID_TEXT : 'Question id',
        QUESTION_SUBMISSION_TEXT : 'Last update: ', //'Submission date',
        QUESTION_FEEDBACK_TEXT : 'Question Feedback',
        QUESTION_FEEDBACK_BUTTON_TEXT : 'Submit Now',
        LIST_APP_POP_UP_BUTTON_TEXT : 'Play Now',
        GAME_MODE_BUTTON_TEXT : 'Play Now',
        USER_BADGES_TITLE : 'My Badges',
        JOURNEY_MODULE_COMPLETE_BUTTON_TEXT : 'Done',
        JOURNEY_CONTENT_RATING_TEXT : "Rate this content",
        JOURNEY_CONTENT_REVIEW_TEXT : "Reviews",
        LIST_APP_QUEST_BUTTON_TEXT : 'Learn now',
        LIST_APP_POLL_BUTTON_TEXT : 'Vote now',
        LIST_APP_KUDOS_BUTTON_TEXT : 'Give Kudos',
        JOURNEY_QUIZ_BADGE_INFO_POP_UP_TEXT : "This test consists of {NUM_OF_QUESTION} questions and you need to have {PASS_PERCENTAGE}% correct to pass it.",
        JOURNEY_QUIZ_BADGE_INFO_POP_UP_TITLE : "Test your knowledge.",
        JOURNEY_QUIZ_BADGE_INFO_POP_UP_BUTTON_TEXT : "Start!",
        JOURNEY_FEEDBACK_SKIP_BUTTON_TEXT : 'Skip',
        USER_MODULE_COMPLETE_TEXT :'Done',
        APP_HOME_RECOMMENDATION_TITLE : 'ACAMS TV',
        APP_HOME_SEE_ALL_TEXT : 'See all',
        APP_HOME_SEE_LESS_TEXT : 'See less',
        APP_HOME_TIMELINE_TITLE : 'Timeline',
        APP_HOME_LEARNING_TITLE : 'Continue learning',
        APP_HOME_TV_TEXT : 'See all',
        APP_HOME_TIMELINE_TEXT : 'See all',
        APP_HOME_LEARNING_TEXT : 'Learn more',
        BADGE_NAME: 'Badges',
        SETTING_BOTTOM_LINE_TEXT_1 : 'Copyright 2019 Acams.app. All rights reserved.',
        SETTING_BOTTOM_LINE_TEXT_2 : 'made with ❤ in ',
        END_LEVEL_TEXT : 'Complete',
        END_LEVEL_ACRONYM_TEXT : 'Complete',
        PROFILE_QUEST_NAME : 'Learn',
        INVALID_VERIFICATION_CODE : 'Invalid verification code.',
        EMAIL_ALREADY_VERIFIED : 'Email is already verified.',
        LANGUAGE_TITLE : 'Select Language',
        MORE_SETTING_TITLE : 'Settings',
        KNOWLEDGE_AREA_LAERNING_TITLE : 'Learn',
        NO_DATA_FOUND : 'No Data Found',
        GET_QUESTION_FACTORY_MODES : 'Question Factory',
        RATE_QUESTION_LIST_TITLE :'Review Questions',
        RATE_QUESTION_SUBMIT_RATING_BUTTON_TEXT :'Submit Rating',
        RATE_THIS_QUESTION_TEXT : 'Rate this question'

    },
}

exports.ERRORS = {
    en :{
        INVALID_COURSE_ID : "Invalid course id",
        UNAUTHORIZED_ACCESS : "Unauthorized access",
        QUESTION_NOT_FOUND : "Question not added to this category yet.",
        CATEGORY_NOT_FOUND : "Category not found",
        KNOWLEDGE_AREA_NOT_FOUND : "Knowledge area not found",
        JOURNEY_MODULE_NOT_FOUND : "Module not found",
        INCORRECT_OPTIONS : "Options are incorrect"
    },
}